#!/bin/sh

### BEGIN INIT INFO
# Provides:          Hogar
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Hogar Bot
# Description:       Hogar Telegram Bot
### END INIT INFO

# Change the next 3 lines to suit where you install your script and what you want to call it
DIR=/opt/hogar
DAEMON=$DIR/hogarctl.py

# This next line determines what user the script runs as.
# Root generally not recommended but necessary if you are using the Raspberry Pi GPIO from Python.
DAEMON_USER=hogar

# Activate the python virtual environment if required
#    . /path_to_virtualenv/activate

. /lib/lsb/init-functions

do_start () {
    log_daemon_msg "Starting Hogar"
    su $DAEMON_USER -s /bin/bash -c "python $DAEMON start quiet"
    log_end_msg $?
}

do_stop () {
    log_daemon_msg "Stopping Hogar"
    python $DAEMON stop quiet
    log_end_msg $?
}

case "$1" in

    start|stop)
        do_${1}
        ;;

    restart|reload|force-reload)
        do_stop
        do_start
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMON_NAME {start|stop|restart}"
        exit 1
        ;;

esac
exit 0
